### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by samuelmoutah** [vinayluzrao/property-management#4]
Authentication /login screen for candidate who can manage property/rent.

**Comment by vinayluzrao** [comment]
the JSON property "appapikey" (for example "appapikey":"28a013c206583bc57fc2cfa4e11dfa14"), should be stored in shared preferences as it is required to make subsequent API calls.

**Comment by vinayluzrao** [comment]
We can omit vendors for now, as the API does not support them.
